name: CI Workflow for Run and Test Python application

on:
  push:
    branches: [ "develop", "feature" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Running Tests
      run: |
        python test_calculator.py
